version: '3.5'

networks:
  default:
    name: api

services:
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    restart: unless-stopped
    ports:
      - '3306:3306'

  php-fpm:
    build:
      context: docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=8
    volumes:
      - ./src:/var/www

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8001:8001"
      - "443:443"


